apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
  labels:
    app: model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
        - name: model-api
          image: model-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MODEL_PATH
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz        # Adjust this to your app's health check path
              port: 8000            # Ensure this is the correct port your app listens on
            initialDelaySeconds: 5  # Delay before the probe starts
            periodSeconds: 10       # How often the probe runs
            failureThreshold: 3     # Number of failures before marking the container as unhealthy
          readinessProbe:
            httpGet:
              path: /readiness      # Adjust this to your app's readiness check path
              port: 8000            # Ensure this is the correct port your app listens on
            initialDelaySeconds: 5  # Delay before the probe starts
            periodSeconds: 10       # How often the probe runs
            failureThreshold: 3     # Number of failures before marking the container as not ready
      serviceAccountName: serviceaccount
      automountServiceAccountToken: false
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
