apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
  labels:
    app: model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
        - name: model-api
          image: ghcr.io/SameaSaeed/my-model-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "/app/models/trained_model.pkl"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
