apiVersion: v1
kind: Service
metadata:
  name: model-api-service
  labels:
    app: model-api
spec:
  selector:
    app: model-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80           # Service port inside the cluster
      targetPort: 8000   # Container port your app listens on
      nodePort: 30080    # External port on each node (optional, or let Kubernetes assign)
