apiVersion: v1
kind: Service
metadata:
  name: model-api-service
  labels:
    app: model-api
spec:
  selector:
    app: model-api
  ports:
    - protocol: TCP
      port: 80         # Port exposed internally in the cluster
      targetPort: 8000 # Port the FastAPI app is listening on
  type: Load Balancer       # You can change to LoadBalancer or NodePort if needed
