name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.8.0
      with:
        minikube_version: 'v1.35.0'
        kubernetes_version: 'v1.32.0'
        driver: none

    - name: Use Minikube Docker daemon
      run: |
        eval $(minikube -p minikube docker-env)

    - name: Build Docker image inside Minikube
      run: |
        docker build -t model-api:latest .

    - name: Apply K8s manifests
      run: |
        kubectl apply -f K8s/deployment.yaml
        kubectl apply -f K8s/service.yaml

    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/model-api --timeout=120s
