name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version

      - name: Start Minikube
        run: minikube start --driver=docker --memory=4g --cpus=2

      - name: Configure Docker to use Minikube's Docker daemon
        run: |
          echo "Setting up Docker env for Minikube"
          eval $(minikube docker-env)

      - name: Build Docker image
        run: docker build -t model-api:latest .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for deployment rollout
        run: kubectl rollout status deployment/model-api --timeout=120s

      - name: Test API availability
        run: |
          # Port-forward in background, wait a bit, then test with curl
          kubectl port-forward svc/model-api-service 8000:80 &
          sleep 10
          curl -f http://localhost:8000/health
