yaml
name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.13.0
      with:
        minikube_version: 'v1.36.0'
        kubernetes_version: 'v1.32.0'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        driver: docker  # Use the 'docker' driver

    - name: Use Minikube Docker daemon
      run: |
        eval $(minikube -p minikube docker-env)

    - name: Build Docker image inside Minikube
      run: |
        docker build -t model-api:latest .

    - name: Apply K8s manifests
      run: |
        kubectl apply -f K8s/deployment.yaml
        kubectl apply -f K8s/service.yaml

    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/model-api --timeout=120s
