name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.8.0
      with:
        minikube version: 'v1.36.0'  # or your preferred version
        kubernetes version: 'v1.26.3'  # or your preferred version
        driver: none   # This runs minikube without virtualization (needed in GitHub runners)
      
    - name: Use Minikube Docker daemon
      run: |
        echo "Setting Docker env to Minikube"
        eval $(minikube -p minikube docker-env)

    - name: Build Docker image inside Minikube
      run: |
        docker build -t model-api:latest .

    - name: Apply K8s manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/model-api --timeout=120s
