name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.8.0
        with:
          minikube version: 'latest'
          kubernetes version: 'v1.27.0'
          driver: docker

      - name: Use Minikube Docker daemon
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t model-api:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f K8s/deployment.yaml
          kubectl apply -f K8s/service.yaml
          kubectl rollout status deployment/model-api --timeout=90s

      - name: Show pods
        run: kubectl get pods -o wide
