name: Build and Deploy to Kind

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Kind
        uses: helm/kind-action@v1.8.0

      - name: Create Kubernetes cluster with Kind
        run: kind create cluster

      - name: Build Docker image and load into Kind
        run: |
          docker build -t model-api:latest .
          kind load docker-image model-api:latest

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/model-api --timeout=60s

      - name: Test the FastAPI endpoint (via port-forward)
        run: |
          kubectl port-forward svc/model-api-service 8000:80 &
          sleep 5
          curl -f http://localhost:8000/docs || exit 1
